[phases.setup]
commands = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[phases.start]
commands = [
  "python app.py"  # Reemplaza "app.py" con el archivo principal de tu aplicación Flask si tiene otro nombre.
]